name: Base conda installation

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test_conda_install:
    name: Test conda installation
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["38", "39"]
        miniconda-version: ["4.10.3", "4.11.0", "4.12.0"]
        poetry-version: ["1.2.0b2", "1.2.0b3", "1.2.0", "1.2.1", "1.2.2"]
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - 
        name: Check out the repo
        uses: actions/checkout@v2
      - 
        name: Set up miniconda
        uses: conda-incubator/setup-miniconda@v2.1.1
        with:
          auto-activate-base: true
          activate-environment: ""
          auto-update-conda: true
          miniconda-version: py${{ matrix.python-version}}_${{ matrix.miniconda-version }}
      -
        name: Install deps and library
        run: |
          python -m pip install poetry==${{ matrix.poetry-version }}
          python -m pip install .
      -
        name: Run tests
        run: |
            python -m pip install pytest pyyaml
            pytest tests -vvv
